CONTRIBUTING.md
=> updated team norms in contributing.md

front-end/src/App.js
added the react router Dom import that prof mentioned in class today
=> added react-router-dom import

front-end/package.json, front-end/src/App.css, front-end/src/App.js, front-end/src/Home.css, front-end/src/Home.js, front-end/src/Login.css, front-end/src/Login.js, front-end/src/Logout.js, front-end/src/PrimaryNav.css, front-end/src/PrimaryNav.js
I initialized the landing pages (App.js, App.css, Home.js, ...) and unified the format.
=> Chenyi landing pages

front-end/src/Login.js, front-end/src/Register.css, front-end/src/Register.js, front-end/src/RestorePassword.css, front-end/src/RestorePassword.js
I added to content in the Register.js and RestorePassword.js files.
But still needs modifications to fake register/restore password requests by creating cases on this website: https://mockaroo.com/
=> Chenyi register restorepwd page

front-end/src/App.css, front-end/src/App.js, front-end/src/ContactUs.js, front-end/src/Footer.css, front-end/src/Footer.js, front-end/src/PrimaryNav.js, front-end/src/TermsOfService.css, front-end/src/TermsOfService.js
there is an issue with footer - need to fix it at the bottom, tried to figure it out but struggling, so please check and fix if you know how
=> footer + contact us+terms of service

front-end/SortBy.js, front-end/src/RecipeList.js, front-end/src/RecipeThumb.js
Added SortBy functionality and added modification to RecipeThumb (needs to be worked on bec somethings are hard coded rn)
=> Hill edits

front-end/src/App.js, front-end/src/ShareRecipe.css, front-end/src/ShareRecipe.js
I set up the share recipe page.
=> setup share-recipe page

front-end/src/App.js, front-end/src/MyIngredients.css, front-end/src/MyIngredients.js
i set up the my ingredient page
=> setup my ingredient page

front-end/src/RecipeList.css, front-end/src/RecipeList.js
changed parts of RecipeList so its more coherent
=> Hill edit2

front-end/src/App.css, front-end/src/Home.js, front-end/src/Login.js, front-end/src/MyIngredients.js, front-end/src/PrimaryNav.js, front-end/src/Register.js, front-end/src/RestorePassword.js
1. I modified the my-ingredient page to allow users to add ingredients by amount.
2. I also modified the format to iPhone 14 screen size
3. emerging problems: the format of the displaying photos using thumb pages does not fit into the new screen size
=> Chenyi modify

front-end/src/SavedRecipes.js
I fixed the background so it will not zoom in when navigating between pages.
I also make the saved-recipe page only visible to logged-in users.
=> fixed background + view saved-recipe only when logges in

front-end/src/App.css
i re-modify the background and also the styling for menu button
=> Chenyi fix background

front-end/src/ShareRecipe.js, front-end/src/setupTests.js
I delete the empty files share.js/css and also add the feature to upload pictures of recipe to the ShareRecipe page.
=> delete share.js/css + add upload img function to ShareRecipe.js

front-end/src/Home.css, front-end/src/Home.js, front-end/src/MyIngredients.js
1. I just remove link from my-ingredient page to ingredient-detail page.
2. I also replaced spoonacular api key so the search function for my-ingredient page should be working again.
3. I centered the links to my-ingredient/my-utensils/saved-recipe pages in the menu bar under home page.
=> remove ingredient-detail link + replace api key + home menu centered

back-end/app.js, front-end/src/RecipeList.js
=> Hill backend

back-end/test/ingredients.test.js
i created the test code for ingredient backend checking
=> test code for ingredient backend

back-end/app.js, back-end/package.json
added connection to Atlas and added mongoose to package.json
=> Random rec

back-end/app.js, back-end/models/utensils.js, back-end/package.json, back-end/routes/contact.js, back-end/routes/utensils.js, back-end/test/utensils.test.js, front-end/package.json, front-end/src/App.css, front-end/src/ContactUs.js, front-end/src/MenuOverlay.css, front-end/src/UtensilThumb.js, front-end/src/Welcome.js
returned styling back to how it was, will work more on it
=> Alex db work + contact us+ npm fix

front-end/src/Welcome.css, front-end/src/Welcome.js
solved the conflict of `<h1>` cannot be placed in `<p>` tag on Welcome page
=> solved tag conflicts

front-end/src/ContactUs.js, front-end/src/Home.css, front-end/src/Login.css, front-end/src/Login.js, front-end/src/MyIngredients.css, front-end/src/MyIngredients.js, front-end/src/PrimaryNav.js, front-end/src/RecipeDetails.js, front-end/src/RecipeList.js, front-end/src/RecipeThumb.js, front-end/src/Register.css, front-end/src/Register.js, front-end/src/ResetPassword.css, front-end/src/ResetPassword.js, front-end/src/SavedRecipes.js, front-end/src/ShareRecipe.js, front-end/src/Welcome.css, front-end/src/Welcome.js
Reverts agiledev-students-spring-2023/final-project-what-s-for-dinner#234
=> Revert "Chenyi deploy"
